---
- name: Get Running Config
  hosts: '{{target}}'
  connection: network_cli
  gather_facts: no



  tasks:
#    - set_fact: mydate="{{lookup('pipe','date +%Y%m%d%H%M%S')}}"
#    - debug: var=mydate
    - shell: 'date +%Y%m%d'
      register: current_run_timestamp

    - name: grab IOS running configuration
      ios_command:
        commands:
          - show run
      register: config

    - name: grab NXOS running configuration
      nxos_command:
        commands: show run
      register: config

    - name: Creates Running Config directory
      file:
        path: /opt/ansible/runningConfig/{{target}}/{{current_run_timestamp.stdout}}
        state: directory
        owner: sanfordg
        group: sanfordg
        mode: 0770

    - name: create backup of configuration
      copy:
        content: "{{config.stdout[0]}}"
        dest: "/opt/ansible/runningConfig/{{target}}/{{current_run_timestamp.stdout}}/{{current_run_timestamp.stdout}}_{{inventory_hostname}}_run_config.txt"

#    - name: Grab running version
#      ios_command:
#        commands:
#          - show version
#      register: version
