---
- name: Get Running Config
  #hosts: '{{target}}'
  hosts: cic
  connection: network_cli
  gather_facts: no



  tasks:

    - name: grab IOS running configuration
      block:
      - ios_facts:
          gather_subset: all

      - name: Creates Running Config directory
        file:
          path: /opt/ansible/runningConfig/{{ ansible_net_hostname }}
          state: directory
          owner: sanfordg
          group: sanfordg
          mode: 0777

      - name: Backup IOS Running Configs
        ios_config:
          backup: yes
          backup_options:
            dir_path:  /opt/ansible/runningConfig/{{ ansible_net_hostname }}

      when: ansible_network_os == 'ios'

    - name: grab NXOS running configuration
      block:
      - nxos_facts:
          gather_subset: all

      - name: Creates Running Config directory
        file:
          path: /opt/ansible/runningConfig/{{ ansible_net_hostname }}
          state: directory
          owner: sanfordg
          group: sanfordg
          mode: 0777

      - name: Backup IOS Running Configs
        nxos_config:
          backup: yes
          backup_options:
            dir_path:  /opt/ansible/runningConfig/{{ ansible_net_hostname }}

      when: ansible_network_os == 'nxos'
