---
- name: Create VLAN on NXOS network info
  #hosts: '{{target}}'
  hosts: test
  connection: network_cli
  gather_facts: no

  tasks:
    - name: include vars #comment out this task if you want to use the Group Varable
      include_vars:
        file: vlans.yml

    - name: Configure VLAN ID and Name it
      nxos_vlan:
        vlan_id: "{{ item.vlan_id }}"
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items: "{{ vlans }}"
      when: ansible_network_os == 'nxos'

    - name: Configure VLAN ID on IOS
      ios_vlan:
        vlan_id: "{{ item.vlan_id }}"
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items: "{{ vlans }}"
      when: ansible_network_os == 'ios'

    - name: show VLAN from NXOS
      nxos_command:
        commands: show vlan brief
      register: show_vlan
      when: ansible_network_os == 'nxos'

    - debug:
        msg: '{{ show_vlan }}'
      when: ansible_network_os == 'nxos'

    - name: show VLAN from IOS
      ios_command:
        commands: show vlan brief
      register: show_vlan
      when: ansible_network_os == 'ios'

    - debug:
        msg: '{{ show_vlan }}'
      when: ansible_network_os == 'ios'

      #var=show_vlan.stdout_lines
