---
- name:
  community.vmware.vmware_host_config_info:
    esxi_hostname: "{{ inventory_hostname }}"
    hostname: "{{ inventory_hostname }}"
    password: "{{ ansible_password }}"
    username: "{{ ansible_user }}"
    validate_certs: no
  register: config_info
  delegate_to: localhost
- name: set facts
  set_fact:
    esxAdmins: "{{ config_info.hosts_info[ansible_hostname + '.' + ansible_domain]['Config.HostAgent.plugins.hostsvc.esxAdminsGroup'] }}"
    DCUIAccess: "{{ config_info.hosts_info[ansible_hostname + '.' + ansible_domain]['DCUI.Access'] }}"
    SysloggloballogHost: "{{ config_info.hosts_info[ansible_hostname + '.' + ansible_domain]['Syslog.global.logHost'] }}"
    SecurityAccountLockFailures: "{{ config_info.hosts_info[ansible_hostname + '.' + ansible_domain]['Security.AccountLockFailures'] }}"
    SecurityAccountUnlockTime: "{{ config_info.hosts_info[ansible_hostname + '.' + ansible_domain]['Security.AccountUnlockTime'] }}"
    AnnotationsWelcomeMessage: "{{ config_info.hosts_info[ansible_hostname + '.' + ansible_domain]['Annotations.WelcomeMessage'] }}"
    ConfigEtcissue: "{{ config_info.hosts_info[ansible_hostname + '.' + ansible_domain]['Config.Etc.issue'] }}"
    ConfigHostAgentloglevel: "{{ config_info.hosts_info[ansible_hostname + '.' + ansible_domain]['Config.HostAgent.log.level'] }}"
- name: create STIG Output file
  local_action:
    module: lineinfile
    path: files/{{ inventory_hostname }}.STIG_output.txt
    create: yes
    line: "This is the findings report for Host {{ inventory_hostname }} using STIG Checklist U_VMware_vSphere_6-0_ESXi_V1R5_STIG"
    insertbefore: BOF
- name: V-63247
  local_action:
    module: lineinfile
    path: files/{{ inventory_hostname }}.STIG_output.txt
    create: yes
    line: "- Vul ID: V-63247, V-63769, V-63897, V-63911 IS a finding, Config.HostAgent.plugins.hostsvc.esxAdminsGroup: {{ config_info.hosts_info[ansible_hostname + '.' + ansible_domain]['Config.HostAgent.plugins.hostsvc.esxAdminsGroup'] }}"
  when: esxAdmins.find("ESX Admins") != -1
- name: V-63247
  local_action:
    module: lineinfile
    path: files/{{ inventory_hostname }}.STIG_output.txt
    create: yes
    line: "- Vul ID: V-63247, V-63769, V-63897, V-63911 IS NOT  a finding, Config.HostAgent.plugins.hostsvc.esxAdminsGroup: {{ config_info.hosts_info[ansible_hostname + '.' + ansible_domain]['Config.HostAgent.plugins.hostsvc.esxAdminsGroup'] }}"
  when: esxAdmins.find("ESX Admins") == -1
  - name: V-63233 check
  shell: grep -i "^password" /etc/pam.d/passwd | grep sufficient
  register: v63233_output
- name: V-63233 output is not a Finding
  local_action:
    module: lineinfile
    path: files/{{ inventory_hostname }}.STIG_output.txt
    create: yes
    line: "- Vul ID: V-63233 IS NOT a finding. {{ v63233_output.stdout }}"
  when: v63233_output.stdout.find("remember=5") != -1
- name: V-63233 output is a Finding
  local_action:
    module: lineinfile
    path: files/{{ inventory_hostname }}.STIG_output.txt
    create: yes
    line: "- Vul ID: V-63233 IS a finding. Missing 'remember=5' from line: {{ v63233_output.stdout }}"
  when: v63233_output.stdout.find("remember=5") == -1
- name: V-63235 output is not a Finding
  local_action:
    module: lineinfile
    path: files/{{ inventory_hostname }}.STIG_output.txt
    create: yes
    line: "- Vul ID: V-63233 IS NOT a finding. {{ v63233_output.stdout }}"
  when: v63233_output.stdout.find("sha512") != -1
- name: V-63235 output is a Finding
  local_action:
    module: lineinfile
    path: files/{{ inventory_hostname }}.STIG_output.txt
    create: yes
    line: "- Vul ID: V-63233 IS a finding. Missing 'sha512' from line: {{ v63233_output.stdout }}"
  when: v63233_output.stdout.find("sha512") == -1
- name: V-63173 output is not a Finding
  local_action:
    module: lineinfile
    path: files/{{ inventory_hostname }}.STIG_output.txt
    create: yes
    line: "- Vul ID: V-63173 IS NOT a finding. {{ DCUIAccess }}"
  when: DCUIAccess == 'root'
- name: V-63173 output is a Finding
  local_action:
    module: lineinfile
    path: files/{{ inventory_hostname }}.STIG_output.txt
    create: yes
    line: "- Vul ID: V-63173 IS a finding.  {{ DCUIAccess }}"
  when: DCUIAccess != 'root'
- name: V-63179 output is not a Finding
  local_action:
    module: lineinfile
    path: files/{{ inventory_hostname }}.STIG_output.txt
    create: yes
    line: "- Vul ID: V-63179 IS NOT a finding. Security.AccountLockFailures: {{ SecurityAccountLockFailures }}"
  when: SecurityAccountLockFailures == '3'
- name: V-63179 output is a Finding
  local_action:
    module: lineinfile
    path: files/{{ inventory_hostname }}.STIG_output.txt
    create: yes
    line: "- Vul ID: V-63179 IS a finding.  Security.AccountLockFailures: {{ SecurityAccountLockFailures }}"
  when: SecurityAccountLockFailures != '3'
- name: V-63181 output is not a Finding
  local_action:
    module: lineinfile
    path: files/{{ inventory_hostname }}.STIG_output.txt
    create: yes
    line: "- Vul ID: V-63181 IS NOT a finding. Security.AccountUnlockTime: {{ SecurityAccountUnlockTime }}"
  when: SecurityAccountUnlockTime == '900'
- name: V-63181 output is a Finding
  local_action:
    module: lineinfile
    path: files/{{ inventory_hostname }}.STIG_output.txt
    create: yes
    line: "- Vul ID: V-63181 IS a finding.  Security.AccountUnlockTime: {{ SecurityAccountUnlockTime }}"
  when: SecurityAccountUnlockTime != '900'

- name: V-63229, V-63509 output is not a Finding
  local_action:
    module: lineinfile
    path: files/{{ inventory_hostname }}.STIG_output.txt
    create: yes
    line: "- Vul ID: V-63229 and V-63509 IS NOT a finding. Config.HostAgent.log.level: {{ ConfigHostAgentloglevel }}"
  when: ConfigHostAgentloglevel == 'info'
- name: V-63229, V-63509 output is a Finding
  local_action:
    module: lineinfile
    path: files/{{ inventory_hostname }}.STIG_output.txt
    create: yes
    line: "- Vul ID: V-63229 and V-63509 IS a finding.  Config.HostAgent.log.level: {{ ConfigHostAgentloglevel }}"
  when: ConfigHostAgentloglevel != 'info'






- name: V-63177, V-63477, V-63833, V-63903, V-63915, V-63921 Review
  local_action:
    module: lineinfile
    path: files/{{ inventory_hostname }}.STIG_output.txt
    create: yes
    line: "- Vul ID: V-63177, V-63477, V-63833, V-63903, V-63915 and V-63921 Review that there is a syslog server  {{ SysloggloballogHost }}"
- name: V-63183 and V-63485 Review
  local_action:
    module: lineinfile
    path: files/{{ inventory_hostname }}.STIG_output.txt
    create: yes
    line: "- Vul ID: V-63183 and V-63485 Review the banner:  {{ AnnotationsWelcomeMessage }}"
- name: V-63185  Review
  local_action:
    module: lineinfile
    path: files/{{ inventory_hostname }}.STIG_output.txt
    create: yes
    line: "- Vul ID: V-63185  Review the banner:  {{ ConfigEtcissue }}"
