---
- hosts: test
  remote_user: sanfordge
  sudo: yes
  tasks:             
 #   - name: create SSH key
 #     user:
 #       name: '{{ username }}'
 #       create_home: yes
 #       generate_ssh_key: yes
 #       ssh_key_bits: 2048
 #       ssh_key_file: .ssh/id_rsa 
    - name: copy SSH to hosts
      authorized_key:
        user: '{{ username }}'
        state: present
        manage_dir: yes
        key: "{{ lookup('file', '/home/{{ username }}/.ssh/id_rsa.pub') }}"
